In [4]:
#1.Write a Python Program to Add Two Matrices
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[8,5,3],[3,5,8]])
print(a+b)

[[ 9  7  6]
 [ 7 10 14]]


In [1]:
#2.Write a Python Program to Multiply Two Matrices?
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[8,5,3],[3,5,8]])
print(a*b)

[[ 8 10  9]
 [12 25 48]]


In [1]:
#3.Write a Python Program to Transpose a Matrix?
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a_transpose = a.transpose()
a_transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [1]:
# 4.Write a Python Program to Sort Words in Alphabetic Order?
s = 'ankush'
l = list(s)
l = sorted(l) 
result = ''.join(l)
print(result)

ahknsu


In [2]:
# 5.Write a Python Program to Remove Punctuation From a String?
import re
string1 = "wow! you are the best."
res = re.sub(r'[^\w\s]','',string1)
print(res)

wow you are the best
